# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_chat(object):
    def setupUi(self, Dialog_chat):
        Dialog_chat.setObjectName("Dialog_chat")
        Dialog_chat.resize(582, 623)
        self.pushButton_refresh = QtWidgets.QPushButton(Dialog_chat)
        self.pushButton_refresh.setGeometry(QtCore.QRect(510, 10, 51, 41))
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.textEdit_message = QtWidgets.QTextEdit(Dialog_chat)
        self.textEdit_message.setGeometry(QtCore.QRect(80, 440, 341, 111))
        self.textEdit_message.setObjectName("textEdit_message")
        self.pushButton_send = QtWidgets.QPushButton(Dialog_chat)
        self.pushButton_send.setGeometry(QtCore.QRect(330, 560, 91, 31))
        self.pushButton_send.setObjectName("pushButton_send")
        self.listWidget_chat = QtWidgets.QListWidget(Dialog_chat)
        self.listWidget_chat.setGeometry(QtCore.QRect(80, 60, 341, 331))
        self.listWidget_chat.setObjectName("listWidget_chat")
        self.label = QtWidgets.QLabel(Dialog_chat)
        self.label.setGeometry(QtCore.QRect(80, 20, 60, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_name = QtWidgets.QLabel(Dialog_chat)
        self.label_name.setGeometry(QtCore.QRect(160, 20, 241, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.label_name.setText("")
        self.label_name.setObjectName("label_name")

        self.retranslateUi(Dialog_chat)
        QtCore.QMetaObject.connectSlotsByName(Dialog_chat)

    def retranslateUi(self, Dialog_chat):
        _translate = QtCore.QCoreApplication.translate
        Dialog_chat.setWindowTitle(_translate("Dialog_chat", "Chat"))
        self.pushButton_refresh.setText(_translate("Dialog_chat", "Refresh"))
        self.pushButton_send.setText(_translate("Dialog_chat", "send"))
        self.label.setText(_translate("Dialog_chat", "Chat with"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_chat = QtWidgets.QDialog()
    ui = Ui_Dialog_chat()
    ui.setupUi(Dialog_chat)
    Dialog_chat.show()
    sys.exit(app.exec_())
