# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comment.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_comment(object):
    def setupUi(self, Dialog_comment):
        Dialog_comment.setObjectName("Dialog_comment")
        Dialog_comment.resize(587, 502)
        self.listWidget_comments = QtWidgets.QListWidget(Dialog_comment)
        self.listWidget_comments.setGeometry(QtCore.QRect(50, 50, 256, 161))
        self.listWidget_comments.setObjectName("listWidget_comments")
        self.label = QtWidgets.QLabel(Dialog_comment)
        self.label.setGeometry(QtCore.QRect(50, 30, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_like = QtWidgets.QPushButton(Dialog_comment)
        self.pushButton_like.setGeometry(QtCore.QRect(50, 220, 91, 31))
        self.pushButton_like.setObjectName("pushButton_like")
        self.pushButton_reply = QtWidgets.QPushButton(Dialog_comment)
        self.pushButton_reply.setGeometry(QtCore.QRect(210, 430, 91, 31))
        self.pushButton_reply.setObjectName("pushButton_reply")
        self.pushButton_comment = QtWidgets.QPushButton(Dialog_comment)
        self.pushButton_comment.setGeometry(QtCore.QRect(50, 430, 91, 31))
        self.pushButton_comment.setObjectName("pushButton_comment")
        self.textEdit_content = QtWidgets.QTextEdit(Dialog_comment)
        self.textEdit_content.setGeometry(QtCore.QRect(50, 320, 251, 91))
        self.textEdit_content.setObjectName("textEdit_content")
        self.pushButton_refresh = QtWidgets.QPushButton(Dialog_comment)
        self.pushButton_refresh.setGeometry(QtCore.QRect(530, 10, 51, 31))
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.listWidget_count = QtWidgets.QListWidget(Dialog_comment)
        self.listWidget_count.setGeometry(QtCore.QRect(320, 50, 141, 161))
        self.listWidget_count.setObjectName("listWidget_count")
        self.label_2 = QtWidgets.QLabel(Dialog_comment)
        self.label_2.setGeometry(QtCore.QRect(320, 30, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog_comment)
        QtCore.QMetaObject.connectSlotsByName(Dialog_comment)

    def retranslateUi(self, Dialog_comment):
        _translate = QtCore.QCoreApplication.translate
        Dialog_comment.setWindowTitle(_translate("Dialog_comment", "Comment"))
        self.label.setText(_translate("Dialog_comment", "Comments on this post"))
        self.pushButton_like.setText(_translate("Dialog_comment", "Like"))
        self.pushButton_reply.setText(_translate("Dialog_comment", "Reply"))
        self.pushButton_comment.setText(_translate("Dialog_comment", "Comment"))
        self.pushButton_refresh.setText(_translate("Dialog_comment", "refresh"))
        self.label_2.setText(_translate("Dialog_comment", "Number of likes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_comment = QtWidgets.QDialog()
    ui = Ui_Dialog_comment()
    ui.setupUi(Dialog_comment)
    Dialog_comment.show()
    sys.exit(app.exec_())
