# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'direct.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_direct(object):
    def setupUi(self, Form_direct):
        Form_direct.setObjectName("Form_direct")
        Form_direct.resize(760, 625)
        self.label = QtWidgets.QLabel(Form_direct)
        self.label.setGeometry(QtCore.QRect(40, 10, 78, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.listWidget_conversation = QtWidgets.QListWidget(Form_direct)
        self.listWidget_conversation.setGeometry(QtCore.QRect(40, 40, 251, 211))
        self.listWidget_conversation.setObjectName("listWidget_conversation")
        self.label_2 = QtWidgets.QLabel(Form_direct)
        self.label_2.setGeometry(QtCore.QRect(40, 320, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.listWidget_other_users_in_network = QtWidgets.QListWidget(Form_direct)
        self.listWidget_other_users_in_network.setGeometry(QtCore.QRect(40, 360, 251, 231))
        self.listWidget_other_users_in_network.setObjectName("listWidget_other_users_in_network")
        self.pushButton_open = QtWidgets.QPushButton(Form_direct)
        self.pushButton_open.setGeometry(QtCore.QRect(340, 50, 111, 41))
        self.pushButton_open.setObjectName("pushButton_open")
        self.pushButton_view_profile_conversation = QtWidgets.QPushButton(Form_direct)
        self.pushButton_view_profile_conversation.setGeometry(QtCore.QRect(340, 110, 111, 41))
        self.pushButton_view_profile_conversation.setObjectName("pushButton_view_profile_conversation")
        self.pushButton_create_conversation = QtWidgets.QPushButton(Form_direct)
        self.pushButton_create_conversation.setGeometry(QtCore.QRect(340, 360, 111, 41))
        self.pushButton_create_conversation.setObjectName("pushButton_create_conversation")
        self.pushButton_view_profile_other = QtWidgets.QPushButton(Form_direct)
        self.pushButton_view_profile_other.setGeometry(QtCore.QRect(340, 420, 111, 41))
        self.pushButton_view_profile_other.setObjectName("pushButton_view_profile_other")
        self.pushButton_refresh = QtWidgets.QPushButton(Form_direct)
        self.pushButton_refresh.setGeometry(QtCore.QRect(670, 20, 61, 41))
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.pushButton_back = QtWidgets.QPushButton(Form_direct)
        self.pushButton_back.setGeometry(QtCore.QRect(630, 550, 101, 41))
        self.pushButton_back.setObjectName("pushButton_back")
        self.label_message = QtWidgets.QLabel(Form_direct)
        self.label_message.setGeometry(QtCore.QRect(340, 490, 231, 31))
        self.label_message.setText("")
        self.label_message.setObjectName("label_message")

        self.retranslateUi(Form_direct)
        QtCore.QMetaObject.connectSlotsByName(Form_direct)

    def retranslateUi(self, Form_direct):
        _translate = QtCore.QCoreApplication.translate
        Form_direct.setWindowTitle(_translate("Form_direct", "Direct"))
        self.label.setText(_translate("Form_direct", "conversations"))
        self.label_2.setText(_translate("Form_direct", "Other users in network"))
        self.pushButton_open.setText(_translate("Form_direct", "Open"))
        self.pushButton_view_profile_conversation.setText(_translate("Form_direct", "View profile"))
        self.pushButton_create_conversation.setText(_translate("Form_direct", "Create conversation"))
        self.pushButton_view_profile_other.setText(_translate("Form_direct", "view profile"))
        self.pushButton_refresh.setText(_translate("Form_direct", "Refresh"))
        self.pushButton_back.setText(_translate("Form_direct", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_direct = QtWidgets.QWidget()
    ui = Ui_Form_direct()
    ui.setupUi(Form_direct)
    Form_direct.show()
    sys.exit(app.exec_())
