# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_login(object):
    def setupUi(self, Dialog_login):
        Dialog_login.setObjectName("Dialog_login")
        Dialog_login.resize(400, 701)
        self.message = QtWidgets.QLabel(Dialog_login)
        self.message.setGeometry(QtCore.QRect(100, 400, 231, 20))
        self.message.setText("")
        self.message.setObjectName("message")
        self.pushButton_login = QtWidgets.QPushButton(Dialog_login)
        self.pushButton_login.setGeometry(QtCore.QRect(100, 430, 181, 31))
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_createacc = QtWidgets.QPushButton(Dialog_login)
        self.pushButton_createacc.setGeometry(QtCore.QRect(100, 300, 91, 21))
        self.pushButton_createacc.setObjectName("pushButton_createacc")
        self.lineEdit_email = QtWidgets.QLineEdit(Dialog_login)
        self.lineEdit_email.setGeometry(QtCore.QRect(100, 150, 181, 31))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.label_email = QtWidgets.QLabel(Dialog_login)
        self.label_email.setGeometry(QtCore.QRect(100, 130, 47, 13))
        self.label_email.setObjectName("label_email")
        self.label_pass = QtWidgets.QLabel(Dialog_login)
        self.label_pass.setGeometry(QtCore.QRect(100, 210, 47, 13))
        self.label_pass.setObjectName("label_pass")
        self.label_welcome = QtWidgets.QLabel(Dialog_login)
        self.label_welcome.setGeometry(QtCore.QRect(160, 50, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_welcome.setFont(font)
        self.label_welcome.setTabletTracking(False)
        self.label_welcome.setTextFormat(QtCore.Qt.AutoText)
        self.label_welcome.setObjectName("label_welcome")
        self.lineEdit_pass = QtWidgets.QLineEdit(Dialog_login)
        self.lineEdit_pass.setGeometry(QtCore.QRect(100, 230, 181, 31))
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.label = QtWidgets.QLabel(Dialog_login)
        self.label.setGeometry(QtCore.QRect(100, 280, 121, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog_login)
        QtCore.QMetaObject.connectSlotsByName(Dialog_login)

    def retranslateUi(self, Dialog_login):
        _translate = QtCore.QCoreApplication.translate
        Dialog_login.setWindowTitle(_translate("Dialog_login", "Dialog"))
        self.pushButton_login.setText(_translate("Dialog_login", "Login"))
        self.pushButton_createacc.setText(_translate("Dialog_login", "create account"))
        self.label_email.setText(_translate("Dialog_login", "email"))
        self.label_pass.setText(_translate("Dialog_login", "password"))
        self.label_welcome.setText(_translate("Dialog_login", "Login"))
        self.label.setText(_translate("Dialog_login", "Don\'t have an account ?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_login = QtWidgets.QDialog()
    ui = Ui_Dialog_login()
    ui.setupUi(Dialog_login)
    Dialog_login.show()
    sys.exit(app.exec_())
