# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_post.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_my_posts(object):
    def setupUi(self, Form_my_posts):
        Form_my_posts.setObjectName("Form_my_posts")
        Form_my_posts.resize(733, 505)
        self.listWidget_my_posts = QtWidgets.QListWidget(Form_my_posts)
        self.listWidget_my_posts.setGeometry(QtCore.QRect(60, 40, 291, 231))
        self.listWidget_my_posts.setObjectName("listWidget_my_posts")
        self.pushButton_add_post = QtWidgets.QPushButton(Form_my_posts)
        self.pushButton_add_post.setGeometry(QtCore.QRect(60, 450, 101, 31))
        self.pushButton_add_post.setObjectName("pushButton_add_post")
        self.label = QtWidgets.QLabel(Form_my_posts)
        self.label.setGeometry(QtCore.QRect(60, 20, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit_content_post = QtWidgets.QTextEdit(Form_my_posts)
        self.textEdit_content_post.setGeometry(QtCore.QRect(60, 340, 291, 101))
        self.textEdit_content_post.setObjectName("textEdit_content_post")
        self.pushButton_back = QtWidgets.QPushButton(Form_my_posts)
        self.pushButton_back.setGeometry(QtCore.QRect(600, 450, 101, 31))
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_refresh = QtWidgets.QPushButton(Form_my_posts)
        self.pushButton_refresh.setGeometry(QtCore.QRect(660, 20, 51, 31))
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.listWidget_counts = QtWidgets.QListWidget(Form_my_posts)
        self.listWidget_counts.setGeometry(QtCore.QRect(380, 40, 181, 231))
        self.listWidget_counts.setObjectName("listWidget_counts")
        self.label_2 = QtWidgets.QLabel(Form_my_posts)
        self.label_2.setGeometry(QtCore.QRect(380, 20, 177, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form_my_posts)
        QtCore.QMetaObject.connectSlotsByName(Form_my_posts)

    def retranslateUi(self, Form_my_posts):
        _translate = QtCore.QCoreApplication.translate
        Form_my_posts.setWindowTitle(_translate("Form_my_posts", "My posts"))
        self.pushButton_add_post.setText(_translate("Form_my_posts", "add post"))
        self.label.setText(_translate("Form_my_posts", "My posts"))
        self.pushButton_back.setText(_translate("Form_my_posts", "Back"))
        self.pushButton_refresh.setText(_translate("Form_my_posts", "Refresh"))
        self.label_2.setText(_translate("Form_my_posts", "Number of likes and comments"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_my_posts = QtWidgets.QWidget()
    ui = Ui_Form_my_posts()
    ui.setupUi(Form_my_posts)
    Form_my_posts.show()
    sys.exit(app.exec_())
