# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notificatons.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_notif(object):
    def setupUi(self, Dialog_notif):
        Dialog_notif.setObjectName("Dialog_notif")
        Dialog_notif.resize(443, 629)
        self.listWidget_notifs = QtWidgets.QListWidget(Dialog_notif)
        self.listWidget_notifs.setGeometry(QtCore.QRect(80, 80, 261, 421))
        self.listWidget_notifs.setObjectName("listWidget_notifs")
        self.label = QtWidgets.QLabel(Dialog_notif)
        self.label.setGeometry(QtCore.QRect(80, 50, 69, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_readAll = QtWidgets.QPushButton(Dialog_notif)
        self.pushButton_readAll.setGeometry(QtCore.QRect(80, 510, 91, 31))
        self.pushButton_readAll.setObjectName("pushButton_readAll")
        self.pushButton_back = QtWidgets.QPushButton(Dialog_notif)
        self.pushButton_back.setGeometry(QtCore.QRect(250, 510, 91, 31))
        self.pushButton_back.setObjectName("pushButton_back")

        self.retranslateUi(Dialog_notif)
        QtCore.QMetaObject.connectSlotsByName(Dialog_notif)

    def retranslateUi(self, Dialog_notif):
        _translate = QtCore.QCoreApplication.translate
        Dialog_notif.setWindowTitle(_translate("Dialog_notif", "Notification"))
        self.label.setText(_translate("Dialog_notif", "Notifications"))
        self.pushButton_readAll.setText(_translate("Dialog_notif", "Read All"))
        self.pushButton_back.setText(_translate("Dialog_notif", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_notif = QtWidgets.QDialog()
    ui = Ui_Dialog_notif()
    ui.setupUi(Dialog_notif)
    Dialog_notif.show()
    sys.exit(app.exec_())
