# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_profile(object):
    def setupUi(self, profile):
        profile.setObjectName("profile")
        profile.resize(753, 579)
        self.label_intro = QtWidgets.QLabel(profile)
        self.label_intro.setGeometry(QtCore.QRect(100, 40, 47, 13))
        self.label_intro.setObjectName("label_intro")
        self.label_about = QtWidgets.QLabel(profile)
        self.label_about.setGeometry(QtCore.QRect(100, 120, 28, 13))
        self.label_about.setObjectName("label_about")
        self.label_featured = QtWidgets.QLabel(profile)
        self.label_featured.setGeometry(QtCore.QRect(80, 200, 47, 13))
        self.label_featured.setObjectName("label_featured")
        self.textEdit_featured = QtWidgets.QTextEdit(profile)
        self.textEdit_featured.setGeometry(QtCore.QRect(130, 200, 181, 51))
        self.textEdit_featured.setObjectName("textEdit_featured")
        self.label_accomplishments = QtWidgets.QLabel(profile)
        self.label_accomplishments.setGeometry(QtCore.QRect(50, 360, 81, 20))
        self.label_accomplishments.setObjectName("label_accomplishments")
        self.label_additional_information = QtWidgets.QLabel(profile)
        self.label_additional_information.setGeometry(QtCore.QRect(20, 430, 106, 13))
        self.label_additional_information.setObjectName("label_additional_information")
        self.textEdit_accomplishments = QtWidgets.QTextEdit(profile)
        self.textEdit_accomplishments.setGeometry(QtCore.QRect(130, 360, 181, 51))
        self.textEdit_accomplishments.setObjectName("textEdit_accomplishments")
        self.textEdit_additional_information = QtWidgets.QTextEdit(profile)
        self.textEdit_additional_information.setGeometry(QtCore.QRect(130, 430, 181, 51))
        self.textEdit_additional_information.setObjectName("textEdit_additional_information")
        self.label_supported_languages = QtWidgets.QLabel(profile)
        self.label_supported_languages.setGeometry(QtCore.QRect(410, 210, 104, 16))
        self.label_supported_languages.setObjectName("label_supported_languages")
        self.label_skills = QtWidgets.QLabel(profile)
        self.label_skills.setGeometry(QtCore.QRect(100, 520, 21, 16))
        self.label_skills.setObjectName("label_skills")
        self.textEdit_intro = QtWidgets.QTextEdit(profile)
        self.textEdit_intro.setGeometry(QtCore.QRect(130, 30, 181, 51))
        self.textEdit_intro.setObjectName("textEdit_intro")
        self.textEdit_about = QtWidgets.QTextEdit(profile)
        self.textEdit_about.setGeometry(QtCore.QRect(130, 120, 181, 51))
        self.textEdit_about.setObjectName("textEdit_about")
        self.checkBox_1 = QtWidgets.QCheckBox(profile)
        self.checkBox_1.setGeometry(QtCore.QRect(540, 210, 101, 17))
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(profile)
        self.checkBox_2.setGeometry(QtCore.QRect(540, 230, 99, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(profile)
        self.checkBox_3.setGeometry(QtCore.QRect(540, 250, 102, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(profile)
        self.checkBox_4.setGeometry(QtCore.QRect(540, 270, 100, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(profile)
        self.checkBox_5.setGeometry(QtCore.QRect(540, 287, 102, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(profile)
        self.checkBox_6.setGeometry(QtCore.QRect(540, 310, 97, 17))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(profile)
        self.checkBox_7.setGeometry(QtCore.QRect(540, 330, 110, 17))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(profile)
        self.checkBox_8.setGeometry(QtCore.QRect(540, 350, 94, 17))
        self.checkBox_8.setObjectName("checkBox_8")
        self.pushButton_save = QtWidgets.QPushButton(profile)
        self.pushButton_save.setGeometry(QtCore.QRect(570, 480, 121, 41))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_back = QtWidgets.QPushButton(profile)
        self.pushButton_back.setGeometry(QtCore.QRect(420, 480, 121, 41))
        self.pushButton_back.setObjectName("pushButton_back")
        self.textEdit_skills = QtWidgets.QTextEdit(profile)
        self.textEdit_skills.setGeometry(QtCore.QRect(130, 500, 181, 51))
        self.textEdit_skills.setObjectName("textEdit_skills")
        self.label_featured_2 = QtWidgets.QLabel(profile)
        self.label_featured_2.setGeometry(QtCore.QRect(70, 290, 56, 13))
        self.label_featured_2.setObjectName("label_featured_2")
        self.textEdit_background = QtWidgets.QTextEdit(profile)
        self.textEdit_background.setGeometry(QtCore.QRect(130, 280, 181, 51))
        self.textEdit_background.setObjectName("textEdit_background")
        self.label_job_status = QtWidgets.QLabel(profile)
        self.label_job_status.setGeometry(QtCore.QRect(400, 40, 51, 13))
        self.label_job_status.setObjectName("label_job_status")
        self.textEdit_job_status = QtWidgets.QTextEdit(profile)
        self.textEdit_job_status.setGeometry(QtCore.QRect(460, 30, 181, 51))
        self.textEdit_job_status.setObjectName("textEdit_job_status")
        self.label_company = QtWidgets.QLabel(profile)
        self.label_company.setGeometry(QtCore.QRect(410, 130, 41, 13))
        self.label_company.setObjectName("label_company")
        self.textEdit_company = QtWidgets.QTextEdit(profile)
        self.textEdit_company.setGeometry(QtCore.QRect(460, 110, 181, 51))
        self.textEdit_company.setObjectName("textEdit_company")

        self.retranslateUi(profile)
        QtCore.QMetaObject.connectSlotsByName(profile)

    def retranslateUi(self, profile):
        _translate = QtCore.QCoreApplication.translate
        profile.setWindowTitle(_translate("profile", "Profile"))
        self.label_intro.setText(_translate("profile", "Intro"))
        self.label_about.setText(_translate("profile", "about"))
        self.label_featured.setText(_translate("profile", "Featured"))
        self.label_accomplishments.setText(_translate("profile", "accomplishments"))
        self.label_additional_information.setText(_translate("profile", "additional_information"))
        self.textEdit_accomplishments.setHtml(_translate("profile", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_supported_languages.setText(_translate("profile", "supported_languages"))
        self.label_skills.setText(_translate("profile", "skills"))
        self.textEdit_intro.setHtml(_translate("profile", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.checkBox_1.setText(_translate("profile", "Persian"))
        self.checkBox_2.setText(_translate("profile", "English"))
        self.checkBox_3.setText(_translate("profile", "Chinese"))
        self.checkBox_4.setText(_translate("profile", "Russian"))
        self.checkBox_5.setText(_translate("profile", "German"))
        self.checkBox_6.setText(_translate("profile", "French"))
        self.checkBox_7.setText(_translate("profile", "Japanese"))
        self.checkBox_8.setText(_translate("profile", "Italian"))
        self.pushButton_save.setText(_translate("profile", "save"))
        self.pushButton_back.setText(_translate("profile", "back"))
        self.label_featured_2.setText(_translate("profile", "background"))
        self.label_job_status.setText(_translate("profile", "job_status"))
        self.label_company.setText(_translate("profile", "conpany"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    profile = QtWidgets.QWidget()
    ui = Ui_profile()
    ui.setupUi(profile)
    profile.show()
    sys.exit(app.exec_())
