# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_signup(object):
    def setupUi(self, Dialog_signup):
        Dialog_signup.setObjectName("Dialog_signup")
        Dialog_signup.resize(390, 716)
        self.message = QtWidgets.QLabel(Dialog_signup)
        self.message.setGeometry(QtCore.QRect(110, 570, 221, 20))
        self.message.setText("")
        self.message.setObjectName("message")
        self.label_3 = QtWidgets.QLabel(Dialog_signup)
        self.label_3.setGeometry(QtCore.QRect(110, 460, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog_signup)
        self.label_2.setGeometry(QtCore.QRect(190, 460, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Dialog_signup)
        self.label_4.setGeometry(QtCore.QRect(110, 440, 81, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_email = QtWidgets.QLineEdit(Dialog_signup)
        self.lineEdit_email.setGeometry(QtCore.QRect(110, 100, 181, 31))
        self.lineEdit_email.setText("")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.label = QtWidgets.QLabel(Dialog_signup)
        self.label.setGeometry(QtCore.QRect(250, 460, 47, 13))
        self.label.setObjectName("label")
        self.label_pass_4 = QtWidgets.QLabel(Dialog_signup)
        self.label_pass_4.setGeometry(QtCore.QRect(110, 320, 111, 16))
        self.label_pass_4.setObjectName("label_pass_4")
        self.lineEdit_fisrtsanme = QtWidgets.QLineEdit(Dialog_signup)
        self.lineEdit_fisrtsanme.setGeometry(QtCore.QRect(110, 280, 181, 31))
        self.lineEdit_fisrtsanme.setObjectName("lineEdit_fisrtsanme")
        self.comboBox_country = QtWidgets.QComboBox(Dialog_signup)
        self.comboBox_country.setGeometry(QtCore.QRect(110, 390, 181, 31))
        self.comboBox_country.setObjectName("comboBox_country")
        for i in range(9):
            self.comboBox_country.addItem("")

        self.comboBox_birth_month = QtWidgets.QComboBox(Dialog_signup)
        self.comboBox_birth_month.setGeometry(QtCore.QRect(188, 480, 41, 22))
        self.comboBox_birth_month.setObjectName("comboBox_birth_month")
        self.comboBox_birth_month.addItem("")
        self.comboBox_birth_month.addItem("")
        self.comboBox_birth_month.addItem("")
        self.comboBox_birth_month.addItem("")
        self.comboBox_birth_month.addItem("")
        self.comboBox_birth_month.addItem("")
        self.comboBox_birth_month.addItem("")
        self.comboBox_birth_month.addItem("")
        self.comboBox_birth_month.addItem("")
        self.comboBox_birth_month.addItem("")
        self.comboBox_birth_month.addItem("")
        self.comboBox_birth_month.addItem("")
        self.label_email = QtWidgets.QLabel(Dialog_signup)
        self.label_email.setGeometry(QtCore.QRect(110, 80, 47, 13))
        self.label_email.setObjectName("label_email")
        self.comboBox_birth_year = QtWidgets.QComboBox(Dialog_signup)
        self.comboBox_birth_year.setGeometry(QtCore.QRect(110, 480, 61, 22))
        self.comboBox_birth_year.setObjectName("comboBox_birth_year")
        for i in range(71):
            self.comboBox_birth_year.addItem("")
        self.lineEdit_lastname = QtWidgets.QLineEdit(Dialog_signup)
        self.lineEdit_lastname.setGeometry(QtCore.QRect(110, 340, 181, 31))
        self.lineEdit_lastname.setObjectName("lineEdit_lastname")
        self.label_pass_3 = QtWidgets.QLabel(Dialog_signup)
        self.label_pass_3.setGeometry(QtCore.QRect(110, 260, 111, 16))
        self.label_pass_3.setObjectName("label_pass_3")
        self.comboBox_birth_day = QtWidgets.QComboBox(Dialog_signup)
        self.comboBox_birth_day.setGeometry(QtCore.QRect(248, 480, 41, 22))
        self.comboBox_birth_day.setObjectName("comboBox_birth_day")
        for i in range(1, 32):
            self.comboBox_birth_day.addItem("")

        self.label_pass = QtWidgets.QLabel(Dialog_signup)
        self.label_pass.setGeometry(QtCore.QRect(110, 140, 47, 13))
        self.label_pass.setObjectName("label_pass")
        self.lineEdit_pass = QtWidgets.QLineEdit(Dialog_signup)
        self.lineEdit_pass.setGeometry(QtCore.QRect(110, 160, 181, 31))
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.pushButton_signup = QtWidgets.QPushButton(Dialog_signup)
        self.pushButton_signup.setGeometry(QtCore.QRect(110, 600, 181, 31))
        self.pushButton_signup.setObjectName("pushButton_signup")
        self.lineEdit_confirmpass = QtWidgets.QLineEdit(Dialog_signup)
        self.lineEdit_confirmpass.setGeometry(QtCore.QRect(110, 220, 181, 31))
        self.lineEdit_confirmpass.setObjectName("lineEdit_confirmpass")
        self.label_welcome = QtWidgets.QLabel(Dialog_signup)
        self.label_welcome.setGeometry(QtCore.QRect(170, 20, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_welcome.setFont(font)
        self.label_welcome.setTabletTracking(False)
        self.label_welcome.setTextFormat(QtCore.Qt.AutoText)
        self.label_welcome.setObjectName("label_welcome")
        self.label_pass_2 = QtWidgets.QLabel(Dialog_signup)
        self.label_pass_2.setGeometry(QtCore.QRect(110, 200, 111, 16))
        self.label_pass_2.setObjectName("label_pass_2")

        self.retranslateUi(Dialog_signup)
        QtCore.QMetaObject.connectSlotsByName(Dialog_signup)

    def retranslateUi(self, Dialog_signup):
        _translate = QtCore.QCoreApplication.translate
        Dialog_signup.setWindowTitle(_translate("Dialog_signup", "Dialog"))
        self.label_3.setText(_translate("Dialog_signup", "year"))
        self.label_2.setText(_translate("Dialog_signup", "month"))
        self.label_4.setText(_translate("Dialog_signup", "date of birth"))
        self.label.setText(_translate("Dialog_signup", "day"))
        self.label_pass_4.setText(_translate("Dialog_signup", "last name"))
        self.comboBox_country.setItemText(0, _translate("Dialog_signup", "Iran"))
        self.comboBox_country.setItemText(1, _translate("Dialog_signup", "United States"))
        self.comboBox_country.setItemText(2, _translate("Dialog_signup", "United Kingdom"))
        self.comboBox_country.setItemText(3, _translate("Dialog_signup", "China"))
        self.comboBox_country.setItemText(4, _translate("Dialog_signup", "Russia"))
        self.comboBox_country.setItemText(5, _translate("Dialog_signup", "Germany"))
        self.comboBox_country.setItemText(6, _translate("Dialog_signup", "France"))
        self.comboBox_country.setItemText(7, _translate("Dialog_signup", "Japan"))
        self.comboBox_country.setItemText(8, _translate("Dialog_signup", "Italy"))
        self.comboBox_birth_month.setItemText(0, _translate("Dialog_signup", "1"))
        self.comboBox_birth_month.setItemText(1, _translate("Dialog_signup", "2"))
        self.comboBox_birth_month.setItemText(2, _translate("Dialog_signup", "3"))
        self.comboBox_birth_month.setItemText(3, _translate("Dialog_signup", "4"))
        self.comboBox_birth_month.setItemText(4, _translate("Dialog_signup", "5"))
        self.comboBox_birth_month.setItemText(5, _translate("Dialog_signup", "6"))
        self.comboBox_birth_month.setItemText(6, _translate("Dialog_signup", "7"))
        self.comboBox_birth_month.setItemText(7, _translate("Dialog_signup", "8"))
        self.comboBox_birth_month.setItemText(8, _translate("Dialog_signup", "9"))
        self.comboBox_birth_month.setItemText(9, _translate("Dialog_signup", "10"))
        self.comboBox_birth_month.setItemText(10, _translate("Dialog_signup", "11"))
        self.comboBox_birth_month.setItemText(11, _translate("Dialog_signup", "12"))
        self.label_email.setText(_translate("Dialog_signup", "email"))

        for i in range(0, 71):
            self.comboBox_birth_year.setItemText(i, _translate("Dialog_signup", str(i+1950)))

        self.label_pass_3.setText(_translate("Dialog_signup", "first name"))
        for i in range(31):
            self.comboBox_birth_day.setItemText(i, _translate("Dialog_signup", str(i+1)))

        self.label_pass.setText(_translate("Dialog_signup", "password"))
        self.pushButton_signup.setText(_translate("Dialog_signup", "Sign up"))
        self.label_welcome.setText(_translate("Dialog_signup", "Sign up"))
        self.label_pass_2.setText(_translate("Dialog_signup", "confirm password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_signup = QtWidgets.QDialog()
    ui = Ui_Dialog_signup()
    ui.setupUi(Dialog_signup)
    Dialog_signup.show()
    sys.exit(app.exec_())
